apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: vote
  namespace: instavote
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  analysis:
    interval: 30s
    threshold: 3
    iterations: 5