---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-dev
  namespace: instavote
spec:
  healthChecks:
  - kind: Deployment
    name: redis-dev
    namespace: instavote
  interval: 1m0s
  path: ./kustomize/redis/dev
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: redis-dev
  targetNamespace: instavote
  timeout: 3m0s
  wait: true
