---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: redis-dev
  namespace: instavote
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/Simoganger/instavote-deploy
