---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote-dev
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: vote-dev
    namespace: instavote
  interval: 1m0s
  path: ./deploy/vote/dev
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: vote-dev
  targetNamespace: instavote
  timeout: 3m0s
  wait: true
